### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by kelvin-273** [harsilspatel/pursuit-of-happiness#3]
Hey Harsil,
What is this repository for?

**Comment by harsilspatel** [comment]
This repo is my and other contributors' -- @darvid7 and @nchlswhttkr -- attempt to organise and collate the information about the companies, which were present at the industry night, and their intern/grad opportunities. Hopefully, it helps someone fulfil the second level of Maslow's hierarchy of needs.

**Comment by kelvin-273** [comment]
Oh ok, That's awesome!
